#!/bin/bash
#
PIDFILE=/var/run/gify-panda.pid

case $1 in
   start)
       # Launch your program as a detached process
       sudo python /opt/gify-panda-app/gify-panda.py 2>/dev/null &
       # Get its PID and store it
       pid=$!
       echo $pid | sudo tee ${PIDFILE} 
       # sudo echo $! > ${PIDFILE} 

   ;;
   stop)
      sudo kill `cat ${PIDFILE}`
      # Now that it's killed, don't forget to remove the PID file
      sudo rm ${PIDFILE}
   ;;
   status)
   if [ -e ${PIDFILE} ]; then
      echo gify-panda is running, pid=`cat ${PIDFILE}`
   else
      echo gify-panda is NOT running
      exit 1
   fi
   ;;

   *)
      echo "usage: gify-panda {start|stop|status}" ;;
esac
exit 0