---
- name: copy gify-panda app
  copy: src=gify-panda-app dest=/opt/ owner=root group=root mode=0755

- name: copy gify-panda daemon
  copy: src=daemon/gify-panda dest=/etc/init.d/ owner=root group=root mode=0755

- name: copy gify-panda monit
  template: src=../templates/monit.template dest=/etc/monit/conf.d/gify-panda owner=root group=root mode=0644

- name: restart service
  monit: name=gify-panda state=restarted

# - name: start gify-panda app
#   service: name=/opt/gify-panda-app/gify-panda.py state=started enabled=yes

