---
- name: counter-panda service
  hosts: base
  become: yes
  roles:   
    - role: counter-panda
      tags: counter-panda
      vars:
        - app_name: counter-panda
        - service_port: 8001
        - service_address: '0.0.0.0'